branch-defaults:
  default:
    environment: django-env
    group_suffix: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-nwestorth-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
